version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" Only for DHCP
      - "3001:80/tcp"
      - "3443:443/tcp"
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      DNSMASQ_LISTENING: all
      WEBPASSWORD: $password
    # Volumes store your data between container upgrades
    volumes:
      - pihole:/etc/pihole/
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
      #- NET_ADMIN
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  pihole
