---
version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    ports:
      - 18080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 3 * * *
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=$APITOKEN
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=$SLACKHOOK
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower-asoka
    labels:
      - "com.centurylinklabs.watchtower.enable=true"