version: "3.8"
services:
  cloudflared:
    image: cloudflare/cloudflared:latest #update the verion where necessary
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    sysctls:
      net.core.rmem_max: 2500000
    environment:
    - TUNNEL_TOKEN=$TOKEN
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
